execute pathogen#infect()

syntax on
filetype plugin indent on


set number
set background=dark
set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4


let g:airline_powerline_fonts = 1
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
set noshowmode
set laststatus=2
set encoding=utf-8
