execute pathogen#infect()

syntax on
filetype plugin indent on


set number
set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4
let g:solarized_termtrans=1
set background=dark
colorscheme wal
let g:solarized_termcolors=256

let g:airline_powerline_fonts = 1
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
set noshowmode
set laststatus=2
set encoding=utf-8
